const $=s=>document.querySelector(s), app=$('#app'), modal=$('#modal'), modalBody=$('#modalBody');
const cases=[
{id:1,name:'Percy Tenantry Column',ghost:'The Bane',questions:['How many lions are there?','What three French words can you find?'],answers:[['5','five'],['esperance en dieu']],letter:'F',tape:'case01.mp3',art:'Percy Tenantry Column.png',ghostArt:'03(1).png'},
{id:2,name:'Bondgate Tower & Playhouse',ghost:'Sir Melodramus',questions:['On the Playhouse, what date is found under GR?','What food does the judge favour most?'],answers:[['1817'],['chicken']],letter:'O',tape:'case02.mp3',art:'Bondgate Tower & Playhouse.png',ghostArt:'04(1).png'},
{id:3,name:"Robertson’s Pant",ghost:'The Witch of the Spring',questions:['When was the Pant erected?','How many columns are on the Pant?'],answers:[['1890'],['8','eight']],letter:'T',tape:'case03.mp3',art:'Robertson’s Pant.png',ghostArt:'05(1).png'},
{id:4,name:"St Paul’s Catholic Church",ghost:'The Ghoulish Nun',questions:['How many doors lead in or out of the church?','How many time keepers do you see?'],answers:[['4','four'],['3','three']],letter:'R',tape:'case04.mp3',art:'St Paul’s Catholic Church.png',ghostArt:'06(1).png'},
{id:5,name:'Market Square',ghost:'The Phantom Carriage',questions:["What colour is the dragon’s bench?",'From the bench, face west. What face looks back at you?'],answers:[['blue'],['clock','clock face']],letter:'C',tape:'case05.mp3',art:'Market Square.png',ghostArt:'07(1).png'},
{id:6,name:'Pottergate Tower',ghost:'The Ragged Sentinel',questions:['Look at the east-side window. How many faces do you see?','In what year was the tower rebuilt?'],answers:[['2','two'],['1768']],letter:'N',tape:'case06.mp3',art:'Pottergate Tower.png',ghostArt:'08(1).png'},
{id:7,name:'Hulne Park Gate',ghost:'The Lantern Keeper',questions:['Study the signs. Where does the public footpath lead?','On the plaque honouring William, what animal is he associated with?'],answers:[['cannon gate','cannongate'],['lion']],letter:'R',tape:'case07.mp3',art:'Hulne Park Gate.png',ghostArt:'09(1).png'},
{id:8,name:"St Michael’s Church",ghost:'The Black Monk',questions:["Thomas Coward’s grave: what did he do in life?",'Beneath the church clock, which pair of names are recorded?'],answers:[['musician'],['william and mary','william & mary']],letter:'O',tape:'case08.mp3',art:'St Michael’s Church.png',ghostArt:'10(1).png'},
{id:9,name:"Lion’s Bridge",ghost:'The White Woman',questions:["What direction is the lion’s tail pointing?",'What animal is engraved in the bridge?'],answers:[['south'],['fox']],letter:'H',tape:'case09.mp3',art:'Lion’s Bridge.png',ghostArt:'ghost bridge.png'},
{id:10,name:'Alnwick Castle',ghost:'The Alnwick Vampire',questions:['What is the statue left above the Percy family crest holding?','In what year did Harry Hotspur die in battle?'],answers:[['axe'],['1403']],letter:'T',tape:'case10.mp3',art:'Alnwick Castle.png',ghostArt:'vampire.png'}];

let state=JSON.parse(localStorage.getItem('agh-v9')||'null')||JSON.parse(localStorage.getItem('agh-v6')||'null')||JSON.parse(localStorage.getItem('agh-v5')||'null')||{name:'',done:[],answers:{},messages:[],seenCalls:[],seenCorrupt:false,readMessages:0,toolHints:[]};
state.done||=[];state.answers||={};state.messages||=[];state.seenCalls||=[];state.toolHints||=[];
state.settings=Object.assign({sound:true,vibration:true,glitches:true,reducedMotion:false,largeText:false,highContrast:false,hints:true,photoIntensity:'normal',autoScrap:false,devMode:false},state.settings||{});
function applySettings(){document.body.classList.toggle('reducedMotion',!!state.settings.reducedMotion);document.body.classList.toggle('largeText',!!state.settings.largeText);document.body.classList.toggle('highContrast',!!state.settings.highContrast);document.querySelectorAll('audio').forEach(a=>{a.muted=!state.settings.sound})}
function vib(pattern){if(state.settings.vibration && navigator.vibrate) navigator.vibrate(pattern)}

const save=()=>{localStorage.setItem('agh-v9',JSON.stringify(state));updateMsgDot()}; const norm=x=>(x||'').toLowerCase().replace(/[^a-z0-9]/g,'');
const descriptions={1:'The Percy Tenantry Column stands at the edge of town, a monumental starting point for Edgar’s trail.',2:'Bondgate Tower and the nearby Playhouse sit on one of Alnwick’s old gateways, where Edgar recorded a theatrical apparition.',3:'Robertson’s Pant is an old stone fountain in the town centre, linked in Edgar’s notes to the Witch of the Spring.',4:'St Paul’s Catholic Church is one of Edgar’s later stops, where his notes begin to feel less certain and more personal.',5:'Alnwick Market Square is the heart of town. Edgar associated it with the sound of an unseen carriage crossing the cobbles.',6:'Pottergate Tower once guarded an approach into Alnwick. Edgar believed something still keeps watch beneath its arch.',7:'Alnwick Castle dominates the town. Edgar came here following the old tale of the Alnwick Vampire.',8:'St Michael’s Church and its churchyard feature heavily in Edgar’s account of the Black Monk.',9:'At Hulne Park Gate, Edgar followed reports of a lonely lantern moving beyond the locked gates.',10:'Lion’s Bridge crosses the River Aln beneath the castle. Edgar’s diary describes a pale woman appearing when mist gathers.'};
let toastQueue=[],toastBusy=false;
function showMessageToast(m){toastQueue.push(m);if(toastBusy)return;nextToast()}
function nextToast(){if(!toastQueue.length){toastBusy=false;return}toastBusy=true;let m=toastQueue.shift(),t=$('#messageToast');t.className='messageToast '+(m.from==='unknown'?'unknownToast':'');t.innerHTML=`<div class="toastTop"><span>${m.from==='harry'?'💬 NEW MESSAGE · HARRY':'⚠ NEW MESSAGE · UNKNOWN'}</span><span>NOW</span></div><div class="toastText">${m.text}</div><div class="toastActions"><button class="btn" onclick="dismissToast()">LATER</button><button class="btn dark" onclick="readToast()">READ MESSAGE</button></div>`;t.classList.remove('hidden');document.querySelector('[data-go=messages]')?.classList.add('newMessagePulse');vib(m.from==='unknown'?[120,80,120]:[80,50,80])}
window.dismissToast=()=>{let t=$('#messageToast');t.classList.add('hidden');document.querySelector('[data-go=messages]')?.classList.remove('newMessagePulse');setTimeout(nextToast,250)};
window.readToast=()=>{dismissToast();go('messages')};
function addMessage(from,text,popup=true){let m={from,text,time:Date.now()};state.messages.push(m);save();if(popup)showMessageToast(m)}
function seedMessages(){if(!state.messages.length){
addMessage('harry',`Morning ${state.name||'there'}. Harry here. Innkeeper, keeper of Edgar Thorncroft’s belongings, and apparently technical support for a dead ghost hunter. This was not in the job description.`);
addMessage('harry','Edgar stayed here while investigating ten hauntings around Alnwick. Then one night he went out with his diary and recorder and never came back. His coat, spare boots and an unpaid bar tab did. I would quite like an explanation for at least two of those things.',false);
addMessage('harry','You have his diary, so follow the locations and send me the answers. I’ll compare them with Edgar’s notes. Start with the Percy Tenantry Column.',false);
addMessage('harry','📷 GHOST CAMERA OPEN: I’ve switched the photo developing room on from the start. Take a photograph at each location and run it through the camera. Edgar photographed almost everything. Mine mostly contain my thumb, so the standard is low.',false);
addMessage('harry','You’ll see some other bits of Edgar’s equipment in the Field Kit. They’re locked for now. If I get anything working, I’ll message you and the site will mark it as OPEN.',false)
}}
function updateMsgDot(){let d=document.querySelector('#msgDot'),n=Math.max(0,state.messages.length-(state.readMessages||0));if(d)d.innerHTML=n?`<span class="navBadge">${n}</span>`:''}
function go(view){history.replaceState(null,'','#'+view);if(!state.name&&view!=='landing')return landing();if(view==='hunt')hunt();if(view==='messages')messages();if(view==='scrapbook')scrapbook();if(view==='tapes')tapes();if(view==='settings')settings();window.scrollTo(0,0);updateMsgDot()}
document.addEventListener('click',e=>{let g=e.target.closest('[data-go]');if(g)go(g.dataset.go)});$('#closeModal').onclick=()=>{stopTools();stopRecorder();modal.classList.add('hidden')};function openModal(html){modalBody.innerHTML=html;modal.classList.remove('hidden')}
function landing(){app.innerHTML=`<section class="landing"><div class="landingCard"><div class="eyebrow">THE ALNWICK GHOST HUNT</div><h1>EDGAR THORNCROFT'S LOST INVESTIGATION</h1><img class="innkeeper" src="assets/innkeeper.png" alt="Harry the Innkeeper"><p class="lead">You have Edgar Thorncroft’s diary. Harry, an Alnwick innkeeper, has been trying to discover what happened to him. Follow the ten locations, answer Edgar’s questions and collect the evidence he left behind.</p><p>Enter the investigator name you want printed on your certificate.</p><input id="landingName" class="nameInput" placeholder="Investigator name" value="${state.name||''}"><br><br><button class="btn dark" onclick="beginHunt()">BEGIN THE HUNT</button></div></section>`}
window.beginHunt=()=>{let n=$('#landingName').value.trim();if(!n){$('#landingName').focus();return}state.name=n;save();seedMessages();go('hunt')};
function hunt(){let n=state.done.length;app.innerHTML=`<section class="page"><div class="paper blogHeader"><img src="assets/innkeeper.png"><div><div class="eyebrow">HARRY'S CASE BOARD</div><h1>${state.name}'s Investigation</h1><p>${n}/10 locations verified. Use Edgar’s diary in the real locations, then check your answers here.</p></div></div><div class="progress"><i style="width:${n*10}%"></i></div><img class="map" src="assets/map.png" alt="Alnwick investigation map"><div class="grid">${cases.map(c=>`<article class="card ${state.done.includes(c.id)?'done':''}"><span class="caseNum">${c.id}</span><h3>${c.name}</h3><p>${c.ghost}</p><span class="pill">${state.done.includes(c.id)?'VERIFIED':'INVESTIGATE'}</span><button class="btn dark" onclick="openCase(${c.id})">OPEN LOCATION</button></article>`).join('')}</div>${n===10?`<div class="post"><h2>ALL TEN LOCATIONS VERIFIED</h2><p>Harry has one final message for you. Something else is waiting in the archive too.</p><button class="btn red" onclick="finale()">OPEN THE ENDING</button></div>`:''}</section>`;maybeCorrupt()}
window.openCase=id=>{let c=cases.find(x=>x.id===id),a=state.answers[id]||['',''];openModal(`<div class="eyebrow">LOCATION ${String(id).padStart(2,'0')}</div><h2>${c.name}</h2><div class="locationHero"><div><p>${descriptions[id]}</p><p><b>Reported haunting:</b> ${c.ghost}</p><div class="tape"><b>EDGAR THORNCROFT · FIELD RECORDING ${String(id).padStart(2,'0')}</b><audio controls src="audio/${c.tape}"></audio><small>Your recording can replace audio/${c.tape} later.</small></div></div><img class="locationArt" src="assets/locations/${String(id).padStart(2,'0')}.png" alt="Illustration of ${c.name}"></div><h3>EDGAR'S QUESTIONS</h3>${[0,1].map(i=>`<div class="answerRow"><b>${c.questions[i]}</b><input id="a${i+1}" class="answer" value="${a[i]||''}" placeholder="Type your answer"><button class="btn" onclick="checkOne(${id},${i})">CHECK</button><div id="fb${i+1}" class="feedback"></div></div>`).join('')}<div id="caseResult"></div><div class="toolDock"><b>FIELD TOOLS</b><p>Harry will unlock Edgar’s equipment as the investigation develops.</p>${toolButtons(id)}</div>`)};
function toolLevel(){return state.done.length}
function unlocked(name){let n=toolLevel();return name==='camera'?true:name==='emf'?n>=2:name==='recorder'?n>=3:name==='spirit'?n>=5:name==='scanner'?n>=6:false}
function toolButtons(id){let defs=[['emf','EMF','tool(\'emf\','+id+')'],['recorder','VOICE RECORDER','voiceRecorder('+id+')'],['camera','GHOST PHOTO','openDeveloper('+id+')'],['spirit','SPIRIT BOX','tool(\'spirit\','+id+')'],['scanner','SCANNER','tool(\'scanner\','+id+')']];return `<div class="caseActions">${defs.map(d=>`<button class="btn dark ${unlocked(d[0])?'':'toolLocked'}" onclick="${unlocked(d[0])?d[2]:`lockedTool('${d[0]}')`}">${unlocked(d[0])?'':'🔒 '}${d[1]}</button>`).join('')}</div><div class="toolStatus">${toolLevel()<2?'Ghost Camera is OPEN. Harry is still trying to wake the other devices up.':'Harry will message you whenever another device becomes OPEN.'}</div>`}
window.lockedTool=n=>openModal(`<div class="eyebrow">FIELD KIT</div><h2>DEVICE NOT CALIBRATED</h2><p>Harry hasn’t managed to get this part of Edgar’s equipment working yet.</p><p class="warning">Continue verifying locations. Harry will message you when another tool is ready.</p>`);
function checkToolUnlocks(){let n=state.done.length,milestones={
2:['emf','🔓 EMF READER OPEN. I found a wiring diagram folded into Edgar’s notes and, against all sensible expectations, the thing responds. Try it at the next location. If it screams, I recommend the traditional scientific method of standing slightly farther away.'],
3:['recorder','🔓 EVP RECORDER OPEN. Edgar kept leaving long silences on his tapes, as if he expected someone to answer him. I’ve enabled the recorder. Ask a question, leave a few seconds, then listen back. And no, breathing heavily into it does not count as evidence.'],
5:['spirit','🔓 SPIRIT BOX OPEN. I have recreated Edgar’s frequency sweeper. His margin note says: ASK WHO IS FOLLOWING ME. Cheerful little sentence, that. Try the same question.'],
6:['scanner','🔓 ENVIRONMENT SCANNER OPEN. Last bit of the kit is responding. Edgar repeatedly logged sudden temperature drops before the strange parts of his recordings. I’m starting to dislike the phrase “strange parts”.']};
if(milestones[n]&&!state.toolHints.includes(n)){state.toolHints.push(n);save();addMessage('harry',milestones[n][1])}}

const storyBeats={
1:[['harry',`First one verified, ${'${state.name}'}. Edgar began at the Tenantry Column too. His first notes are almost annoyingly cheerful: “Ten locations. Ten stories. Let us see how many survive proper scrutiny.” Famous last words, perhaps. Nine to go.`]],
2:[['harry','Bondgate matches Edgar’s second entry exactly. There is a line underneath that I hadn’t noticed before: “Someone crossed beneath the arch after me. No footsteps.” That is either atmospheric writing or a very poor advert for walking alone at night.'],['unknown','ARE YOU FOLLOWING HIM?'],['harry','Did you just get a message from a number the site does not recognise? Because something connected for three seconds and vanished. Technical diagnosis: weird.']],
3:[['harry','Robertson’s Pant is where Edgar’s handwriting changes. He writes that the route feels deliberate, as though the locations are pointing him somewhere. Then there is a sentence in different handwriting: “KEEP WALKING.” Edgar claimed he did not write it.'],['unknown','HE STOOD WHERE YOU ARE STANDING.']],
4:[['harry','I’ve compared your progress with Edgar’s timestamps. Same locations. Same order. Nearly the same gaps between entries. I never programmed an order into this site, which is either fascinating paranormal evidence or spectacularly poor web development on my part. I’m hoping for the second one.'],['unknown','IT ISN’T.']],
5:[['harry','Market Square. Edgar’s tape mentions the carriage, then suddenly says: “There’s someone beside the clock. He’s looking at me.” He says HE, not ghost, not driver, not apparition. I don’t love that distinction.'],['unknown',`I CAN SEE YOU, ${'${state.name}'}.`]],
6:[['harry',`Right. The site just wrote your name into a file I did not create. I’m going to say this once: if anything feels wrong, stop. Edgar did not stop.`],['unknown','YOU ARE WALKING THE SAME PATH.'],['unknown','DO NOT LET HARRY CLOSE THE CONNECTION.']],
7:[['harry','Edgar’s next note is the first time he stops calling these things ghosts. He writes: “They are impressions. Not attached to places. Appearing along a route. My route.” Then he underlined MY three times.'],['harry','I’ve stopped laughing at the notes, by the way. Just so we’re clear on the current mood.']],
8:[['harry','I found the missing end of one of Edgar’s recordings. He says he has seen the same man five times, always behind him, carrying a notebook. Then: “I saw his face. It was mine.”'],['unknown','NOW YOU UNDERSTAND.']],
9:[['harry',`Edgar’s final theory is worse. He thought a haunting might be a memory travelling the wrong direction through time. He wrote: “Perhaps one need not be dead to leave a ghost. Perhaps one need only disappear.” ${'${state.name}'}, I think he knew someone was following his investigation before you were even born.`],['unknown','HE WAS NOT FOLLOWING YOU.'],['unknown','YOU WERE FOLLOWING EACH OTHER.']],
10:[['harry',`All ten. ${'${state.name}'}, don’t move on yet. Edgar’s last tape ends at the castle, but there’s another audio file hidden after it. The timestamp is impossible. It was created today.`],['unknown',`THAT’S CORRECT, ${'${state.name}'}.`],['unknown','YOU FOUND ME.']]
};
function storyAfterCase(id){let beats=storyBeats[id]||[];beats.forEach((b,i)=>setTimeout(()=>addMessage(b[0],b[1]),500+i*1800))}

window.checkOne=(id,i)=>{let c=cases.find(x=>x.id===id),v=$(`#a${i+1}`).value;state.answers[id]=state.answers[id]||['',''];state.answers[id][i]=v;let ok=c.answers[i].some(a=>norm(a)===norm(v));let fb=$(`#fb${i+1}`);fb.className='feedback '+(ok?'good':'bad');fb.textContent=ok?'✓ That’s correct. Harry has verified it.':'Hmm… that’s not right. Have another look at Edgar’s diary and the location.';save();let vals=state.answers[id],all=[0,1].every(j=>c.answers[j].some(a=>norm(a)===norm(vals[j]||'')));if(all&&!state.done.includes(id)){state.done.push(id);save();$('#caseResult').innerHTML='<div class="post"><h3>✓ LOCATION VERIFIED</h3><p>Evidence added to your investigation. Watch for Harry’s message.</p></div>';storyAfterCase(id);checkToolUnlocks();if([2,6,10].includes(id))setTimeout(()=>unknownCall(id),3200);setTimeout(()=>maybeCorrupt(true),5200)}};
function messages(){state.readMessages=state.messages.length;save();app.innerHTML=`<section class="page messages"><h1 class="sectionTitle">MESSAGES</h1><div class="paper"><p>Messages connected to the Thorncroft investigation. Harry’s number is saved. The other one isn’t.</p></div><div class="thread">${state.messages.map(m=>`<div class="bubble ${m.from}"><small>${m.from==='harry'?'HARRY · THE INNKEEPER':'UNKNOWN NUMBER'}</small>${m.text}</div>`).join('')}</div></section>`}
function unknownCall(id){if(state.seenCalls.includes(id))return;state.seenCalls.push(id);save();let lines={1:'Are you following him?',2:'He asked the same questions.',3:'Stop looking in the water.',4:'He could hear me too.',5:'The carriage was not empty.',6:'The gate is still watched.',7:'He found what was buried.',8:'Do you smell smoke?',9:'Do not follow the lantern.',10:'You found all ten. Now find Edgar.'};$('#callOverlay').classList.remove('hidden');$('#callOverlay').innerHTML=`<div><div class="caller">INCOMING CALL</div><div class="callNumber">UNKNOWN</div><p>NO CALLER ID</p><div class="callButtons"><button class="roundCall decline" onclick="endCall(${id},false)">✕</button><button class="roundCall accept" onclick="answerCall(${id})">☎</button></div></div>`;vib([500,300,500,300,500])}
window.answerCall=id=>{$('#callOverlay').innerHTML=`<div><div class="caller">UNKNOWN</div><div class="callNumber">00:${String(3+id%4).padStart(2,'0')}</div><p class="ghostMsg">“${({1:'Are you following him?',2:'He asked the same questions.',3:'Stop looking in the water.',4:'He could hear me too.',5:'The carriage was not empty.',6:'The gate is still watched.',7:'He found what was buried.',8:'Do you smell smoke?',9:'Do not follow the lantern.',10:'You found all ten. Now find Edgar.'})[id]}”</p><button class="btn red" onclick="endCall(${id},true)">CALL ENDED</button></div>`}
window.endCall=(id,answered)=>{let txt=({1:'Are you following him?',2:'He asked the same questions.',3:'Stop looking in the water.',4:'He could hear me too.',5:'The carriage was not empty.',6:'The gate is still watched.',7:'He found what was buried.',8:'Do you smell smoke?',9:'Do not follow the lantern.',10:'You found all ten. Now find Edgar.'})[id];$('#callOverlay').classList.add('hidden');if(answered)addMessage('unknown',txt);if(id>=5)addMessage('harry','Did you just get a call? I didn’t give your number to anyone.');save()}
function tapes(){app.innerHTML=`<section class="page"><h1 class="sectionTitle">EDGAR'S TAPES</h1><div class="paper"><p>Field recordings recovered with Edgar’s diary. Each tape unlocks after you verify that location.</p></div><div class="grid">${cases.map(c=>`<article class="card ${state.done.includes(c.id)?'':'locked'}"><div class="eyebrow">FIELD RECORDING ${String(c.id).padStart(2,'0')}</div><h3>${c.name}</h3>${state.done.includes(c.id)?`<audio controls src="audio/${c.tape}"></audio>`:'<p>LOCKED</p>'}</article>`).join('')}</div></section>`}
async function scrapbook(){let photos=await dbAll();app.innerHTML=`<section class="page"><h1 class="sectionTitle">MY PARANORMAL SCRAPBOOK</h1><div class="paper"><p><b>${state.name}</b> · ${state.done.length}/10 locations · ${photos.length} ghost photographs</p></div>${photos.length?`<div class="scrapGrid">${photos.map((p,i)=>`<figure class="polaroid" style="--r:${[-2,1,-1,2][i%4]}deg"><img src="${p.data}"><p>${p.site}<br>${new Date(p.time).toLocaleDateString()}</p><button class="btn" onclick="downloadPhoto(${p.id})">DOWNLOAD</button></figure>`).join('')}</div>`:'<div class="paper"><p>No ghost photographs yet. Add one from any location page.</p></div>'}</section>`}
let activePhotoCase=1;window.openDeveloper=id=>{activePhotoCase=id;let c=cases.find(x=>x.id===id);openModal(`<div class="eyebrow">GHOST PHOTOGRAPH</div><h2>${c.name}</h2><p>Take a photograph at the location or choose one you already took. The game will develop an apparition over it.</p><button class="btn dark" onclick="choosePhoto()">TAKE / ADD PHOTO</button><p class="warning">The apparition is a theatrical game effect.</p><div id="developArea"></div>`)};window.choosePhoto=()=>$('#photoInput').click();$('#photoInput').onchange=e=>{let f=e.target.files[0];if(!f)return;let r=new FileReader();r.onload=()=>develop(r.result,activePhotoCase);r.readAsDataURL(f);e.target.value=''};
function develop(src,id){let img=new Image();img.onload=()=>{let max=1400,s=Math.min(1,max/img.width),w=Math.round(img.width*s),h=Math.round(img.height*s),cv=document.createElement('canvas');cv.width=w;cv.height=h;let x=cv.getContext('2d');x.drawImage(img,0,0,w,h);x.fillStyle='rgba(73,31,27,.10)';x.fillRect(0,0,w,h);
compositeApparition(x,w,h,id,()=>{x.fillStyle='rgba(255,255,255,.62)';x.font=Math.max(16,w/45)+'px Courier New';x.fillText('ALNWICK GHOST HUNT · '+cases[id-1].name,20,h-24);let data=cv.toDataURL('image/jpeg',.9);$('#developArea').innerHTML='<div class="cameraStage"></div><p class="ghostMsg">ANOMALY DEVELOPED: '+cases[id-1].ghost+'</p><div class="caseActions"><button class="btn dark" id="addScrap">ADD TO SCRAPBOOK</button><a class="btn" href="'+data+'" download="alnwick-case-'+id+'.jpg">DOWNLOAD PHOTO</a></div>';$('#developArea .cameraStage').appendChild(cv);let add=async()=>{await dbAdd({data,site:cases[id-1].name,time:Date.now()});$('#addScrap').textContent='ADDED ✓'};$('#addScrap').onclick=add;if(state.settings.autoScrap)add()})};img.src=src}
function drawGhost(x,w,h,id){
  // Fallback used only if the supplied apparition image cannot load.
  x.save();let px=w*(.18+Math.random()*.55),py=h*(.08+Math.random()*.25),gw=Math.min(w,h)*(.2+Math.random()*.12);
  x.globalAlpha=state.settings.photoIntensity==='subtle'?.10:state.settings.photoIntensity==='obvious'?.38:.22;
  x.shadowColor='white';x.shadowBlur=24;x.fillStyle='#eef4ed';
  x.beginPath();x.arc(px,py+gw*.25,gw*.22,0,Math.PI*2);x.fill();
  x.beginPath();x.moveTo(px-gw*.35,py+gw*.42);x.quadraticCurveTo(px,py+gw*.15,px+gw*.35,py+gw*.42);x.lineTo(px+gw*.5,py+gw*1.35);x.quadraticCurveTo(px,py+gw*1.1,px-gw*.5,py+gw*1.35);x.closePath();x.fill();x.restore()
}
function compositeApparition(ctx,w,h,id,done){
  let g=new Image(), c=cases[id-1], path='assets/ghosts/'+encodeURIComponent(c.ghostArt);
  g.onload=()=>{ctx.save();let intensity=state.settings.photoIntensity==='subtle'?.13:state.settings.photoIntensity==='obvious'?.48:.27;
    ctx.globalAlpha=intensity;ctx.filter='grayscale(1) sepia(.18) contrast(1.08)';
    let gw=w*(.24+Math.random()*.28),gh=gw*(g.height/g.width); if(gh>h*.78){gh=h*.78;gw=gh*(g.width/g.height)}
    let gx=Math.random()*Math.max(1,w-gw),gy=h-gh-(Math.random()*h*.08);
    if(Math.random()>.5){ctx.translate(w,0);ctx.scale(-1,1);gx=w-gx-gw}
    ctx.drawImage(g,gx,gy,gw,gh);ctx.restore();done()
  };g.onerror=()=>{drawGhost(ctx,w,h,id);done()};g.src=path
}
let timers=[],audioCtx=null,noiseNode=null,mediaRecorder=null,recordStream=null,recordChunks=[];function stopTools(){timers.forEach(clearInterval);timers=[];if(noiseNode){try{noiseNode.stop()}catch{}noiseNode=null}if(audioCtx){audioCtx.close();audioCtx=null}}function stopRecorder(){if(mediaRecorder&&mediaRecorder.state!=='inactive')mediaRecorder.stop();if(recordStream)recordStream.getTracks().forEach(t=>t.stop());recordStream=null}
$('#kitBtn').onclick=()=>openModal(`<div class="eyebrow">FIELD KIT</div><h2>Edgar's Recovered Equipment</h2><p>Harry is restoring the devices as your investigation progresses.</p>${toolButtons(0)}<p class="warning">The detector readings and paranormal responses are fictional game effects. The voice recorder uses your real microphone locally.</p>`);
window.tool=(t,id=0)=>{stopTools();if(t==='emf'){modalBody.innerHTML=`<div class="toolScreen"><h2>EMF DETECTOR</h2><div class="bigReading" id="emfN">0.4</div><div class="meter"><i id="emfBar"></i></div><p id="emfMsg">SCANNING...</p><button class="btn red" onclick="stopTools();$('#emfMsg').textContent='STOPPED'">STOP</button></div>`;timers.push(setInterval(()=>{let spike=Math.random()<.08,v=spike?4+Math.random():.2+Math.random()*1.4;$('#emfN').textContent=v.toFixed(1);$('#emfBar').style.width=Math.min(100,v*20)+'%';if(spike){$('#emfMsg').textContent=state.done.length>=6?'SIGNAL: E. THORNCROFT':'ANOMALY';vib(120)}},500))}if(t==='scanner'){modalBody.innerHTML=`<div class="toolScreen"><h2>ENVIRONMENT SCANNER</h2><div class="bigReading" id="temp">11.8°C</div><p id="scanMsg">MONITORING...</p><button class="btn red" onclick="stopTools();$('#scanMsg').textContent='STOPPED'">STOP</button></div>`;timers.push(setInterval(()=>{let drop=Math.random()<.09,v=drop?3+Math.random()*3:9+Math.random()*6;$('#temp').textContent=v.toFixed(1)+'°C';if(drop){$('#scanMsg').textContent='COLD SPOT DETECTED';vib([80,50,80])}},800))}if(t==='spirit'){modalBody.innerHTML=`<div class="toolScreen"><h2>SPIRIT BOX</h2><div class="freq" id="freq">87.5</div><p id="word">SWEEPING...</p><button class="btn red" onclick="stopTools();$('#word').textContent='STOPPED'">STOP</button></div>`;startNoise();let pools={7:['BLOOD','BURIED','EDGAR'],8:['SMOKE','MONK','LISTEN'],9:['WILLIAM','LANTERN','DON’T FOLLOW'],10:['WATER','MIST','FIND ME']};let words=pools[id]||(state.done.length>=6?['EDGAR','JOURNAL','LISTEN','FOLLOWING','NOT GONE']:['WATCH','WATER','GATE','COLD','LEAVE']);timers.push(setInterval(()=>{$('#freq').textContent=(87.5+Math.random()*20).toFixed(1);if(Math.random()<.13){$('#word').textContent=words[Math.floor(Math.random()*words.length)];vib(70)}},150))}}
function startNoise(){if(!state.settings.sound)return;try{audioCtx=new (window.AudioContext||window.webkitAudioContext)();let b=audioCtx.createBuffer(1,audioCtx.sampleRate*2,audioCtx.sampleRate),d=b.getChannelData(0);for(let i=0;i<d.length;i++)d[i]=(Math.random()*2-1)*.08;noiseNode=audioCtx.createBufferSource();noiseNode.buffer=b;noiseNode.loop=true;noiseNode.connect(audioCtx.destination);noiseNode.start()}catch{}}
window.voiceRecorder=async id=>{stopTools();openModal(`<div class="recording"><h2>VOICE / EVP RECORDER</h2><p>Ask a question, leave a few seconds of silence, then stop the recording and listen back.</p><p id="recStatus">READY</p><button id="recStart" class="btn dark">START RECORDING</button><button id="recStop" class="btn red" disabled>STOP</button><div id="recPlayback"></div><p class="warning">This records through your device microphone. Nothing is uploaded.</p></div>`);$('#recStart').onclick=async()=>{try{recordStream=await navigator.mediaDevices.getUserMedia({audio:true});recordChunks=[];mediaRecorder=new MediaRecorder(recordStream);mediaRecorder.ondataavailable=e=>recordChunks.push(e.data);mediaRecorder.onstop=()=>{let blob=new Blob(recordChunks,{type:mediaRecorder.mimeType}),url=URL.createObjectURL(blob);$('#recPlayback').innerHTML=`<p><b>PLAYBACK</b></p><audio controls src="${url}"></audio>${state.done.length>=5?'<p class="ghostMsg">ARCHIVE ANALYSIS: faint voice-like anomaly detected. “...following...”</p>':''}`;recordStream.getTracks().forEach(t=>t.stop())};mediaRecorder.start();$('#recStatus').innerHTML='<span class="recDot"></span> RECORDING';$('#recStart').disabled=true;$('#recStop').disabled=false}catch(e){$('#recStatus').textContent='Microphone permission was not available.'}};$('#recStop').onclick=()=>{if(mediaRecorder?.state==='recording')mediaRecorder.stop();$('#recStatus').textContent='STOPPED';$('#recStop').disabled=true}}
function settings(){applySettings();app.innerHTML=`<section class="page settingsPage"><h1 class="sectionTitle">SETTINGS</h1>
<div class="paper"><div class="eyebrow">INVESTIGATOR PROFILE</div><h2>${state.name}</h2><label>Certificate / investigator name</label><div class="settingRow"><input id="setName" class="answer" value="${state.name}"><button class="btn dark" onclick="saveNameSetting()">SAVE NAME</button></div></div>
<div class="paper"><div class="eyebrow">EXPERIENCE</div><h2>Sound & Effects</h2>${toggleSetting('sound','Sound & recordings','Mute site audio without changing your phone volume.')}${toggleSetting('vibration','Vibration','Vibrate for messages, calls and detector anomalies.')}${toggleSetting('glitches','Website corruption','Show story glitches and corrupted-screen effects.')}${toggleSetting('reducedMotion','Reduced motion','Reduce pulsing, shaking and animated transitions.')}</div>
<div class="paper"><div class="eyebrow">ACCESSIBILITY</div><h2>Display</h2>${toggleSetting('largeText','Larger text','Increase text size across the investigation.')}${toggleSetting('highContrast','High contrast','Increase contrast between paper, text and controls.')}${toggleSetting('hints','Hints','Allow Harry’s hint prompts when available.')}</div>
<div class="paper"><div class="eyebrow">SPECTRAL CAMERA</div><h2>Ghost photographs</h2><label>Apparition intensity</label><select id="photoIntensity" class="answer" onchange="setPhotoIntensity(this.value)"><option value="subtle" ${state.settings.photoIntensity==='subtle'?'selected':''}>Subtle</option><option value="normal" ${state.settings.photoIntensity==='normal'?'selected':''}>Normal</option><option value="obvious" ${state.settings.photoIntensity==='obvious'?'selected':''}>Obvious</option></select>${toggleSetting('autoScrap','Auto-add developed photos','Automatically add developed ghost photographs to the scrapbook.')}</div>
<div class="paper"><div class="eyebrow">INVESTIGATION DATA</div><h2>Progress</h2><p><b>${state.done.length}/10</b> locations verified · <b>${state.messages.length}</b> story messages received.</p><div class="caseActions"><button class="btn" onclick="replayStory()">REPLAY STORY MESSAGES</button><button class="btn red" onclick="confirmReset()">RESET INVESTIGATION</button></div><p class="warning">Reset removes answers, messages, story progress, equipment unlocks and saved scrapbook photos from this browser.</p></div>
<div class="paper"><div class="eyebrow">ABOUT</div><h2>Alnwick Ghost Hunt</h2><p>Version 9 · Thorncroft Archive build</p><button class="versionTap" onclick="tapVersion()">BUILD 9.0.0</button>${state.settings.devMode?devPanel():''}</div></section>`;applySettings()}
function toggleSetting(key,title,desc){return `<label class="settingToggle"><span><b>${title}</b><small>${desc}</small></span><input type="checkbox" ${state.settings[key]?'checked':''} onchange="setSetting('${key}',this.checked)"><i></i></label>`}
window.setSetting=(k,v)=>{state.settings[k]=v;save();applySettings();if(k==='sound')document.querySelectorAll('audio').forEach(a=>a.muted=!v)};
window.setPhotoIntensity=v=>{state.settings.photoIntensity=v;save()};
window.saveNameSetting=()=>{let n=$('#setName').value.trim();if(!n)return;state.name=n;save();settings();showMessageToast({from:'harry',text:`Right then, ${n}. I’ve updated the investigation file.`})};
window.replayStory=()=>{state.readMessages=0;save();go('messages')};
window.confirmReset=()=>openModal(`<div class="eyebrow">DANGER ZONE</div><h2>Reset the investigation?</h2><p>This will erase all clue answers, story messages, calls, equipment unlocks and scrapbook photographs stored on this device.</p><p>Type <b>RESET</b> to confirm.</p><input id="resetWord" class="answer" autocomplete="off" placeholder="Type RESET"><button class="btn red" onclick="resetInvestigation()">ERASE INVESTIGATION</button>`);
window.resetInvestigation=async()=>{if(($('#resetWord')?.value||'').trim().toUpperCase()!=='RESET'){alert('Type RESET exactly to confirm.');return}try{indexedDB.deleteDatabase('alnwickGhostArchive')}catch{}localStorage.removeItem('agh-v9');localStorage.removeItem('agh-v6');localStorage.removeItem('agh-v5');state={name:'',done:[],answers:{},messages:[],seenCalls:[],seenCorrupt:false,readMessages:0,toolHints:[],settings:{sound:true,vibration:true,glitches:true,reducedMotion:false,largeText:false,highContrast:false,hints:true,photoIntensity:'normal',autoScrap:false,devMode:false}};modal.classList.add('hidden');save();landing()};
let versionTaps=0,versionTimer=null;window.tapVersion=()=>{versionTaps++;clearTimeout(versionTimer);versionTimer=setTimeout(()=>versionTaps=0,2500);if(versionTaps>=7){state.settings.devMode=!state.settings.devMode;versionTaps=0;save();settings()}};
function devPanel(){return `<div class="devPanel"><div class="eyebrow">DEVELOPER / TEST MODE</div><h3>Story controls</h3><p>Hidden in the public experience. Tap the build number seven times to disable it.</p><div class="caseActions"><button class="btn" onclick="devCompleteNext()">COMPLETE NEXT CASE</button><button class="btn" onclick="devUnlockAllTools()">UNLOCK ALL TOOLS</button><button class="btn" onclick="devHarry()">TRIGGER HARRY MESSAGE</button><button class="btn" onclick="devUnknown()">TRIGGER UNKNOWN</button><button class="btn" onclick="devCall()">TRIGGER CALL</button><button class="btn" onclick="maybeCorrupt(true)">TRIGGER CORRUPTION</button><button class="btn red" onclick="devCompleteAll()">COMPLETE ALL 10</button></div></div>`}
window.devCompleteNext=()=>{let c=cases.find(c=>!state.done.includes(c.id));if(c){state.done.push(c.id);save();checkToolUnlocks();settings()}};
window.devCompleteAll=()=>{state.done=cases.map(c=>c.id);save();settings()};
window.devUnlockAllTools=()=>{state.done=[1,2,3,4,5,6,...state.done.filter(x=>x>6)];state.done=[...new Set(state.done)].sort((a,b)=>a-b);save();settings()};
window.devHarry=()=>addMessage('harry','Test message from Harry. The popup system is working.');
window.devUnknown=()=>addMessage('unknown','YOU SHOULD NOT BE ABLE TO READ THIS.');
window.devCall=()=>unknownCall(10);

function maybeCorrupt(force=false){let n=state.done.length;if(!state.settings.glitches&&!force)return;if(n<5)return;if(force||(!state.seenCorrupt&&n>=5)){state.seenCorrupt=true;save();setTimeout(()=>{$('#glitchFlash').classList.remove('hidden');$('#glitchFlash').innerHTML='<div>HARRY CANNOT SEE THIS<br><small style="font-size:.35em">ARE YOU FOLLOWING ME?</small></div>';setTimeout(()=>{$('#glitchFlash').classList.add('hidden');$('#glitchFlash').innerHTML='';if(!state.messages.some(m=>m.text.includes('HARRY CANNOT')))addMessage('unknown','HARRY CANNOT SEE THIS. KEEP FOLLOWING THE DIARY.')},1900)},500)}}
window.finale=()=>{openModal(`<div class="corruptText"><div class="eyebrow">UNKNOWN CONNECTION</div><h2>THE LAST MESSAGE</h2><p>YOU FOLLOWED MY FOOTSTEPS.</p><p>YOU FOUND WHAT I LEFT BEHIND.</p><p>I AM NOT WHERE HARRY THINKS I AM.</p><p>LISTEN TO THE DIARY.</p></div><button class="btn dark" onclick="showCertificate()">CLAIM GHOST HUNTER CERTIFICATE</button>`)}
window.showCertificate=()=>{modalBody.innerHTML=`<div class="eyebrow">INVESTIGATION COMPLETE</div><h2>Ghost Hunter Certificate</h2><div id="certStage" class="certificateStage"></div><button id="certDownload" class="btn dark">DOWNLOAD CERTIFICATE</button>`;let img=new Image();img.onload=()=>{let cv=document.createElement('canvas');cv.width=img.width;cv.height=img.height;let x=cv.getContext('2d');x.drawImage(img,0,0);x.fillStyle='#13263c';x.textAlign='center';x.font=`bold ${Math.round(img.width*.045)}px Georgia`;x.fillText(state.name,img.width*.51,img.height*.48);$('#certStage').appendChild(cv);$('#certDownload').onclick=()=>{let a=document.createElement('a');a.href=cv.toDataURL('image/png');a.download=`${state.name.replace(/\s+/g,'-')}-Alnwick-Ghost-Hunter-Certificate.png`;a.click()}};img.src='assets/certificate.png'}
function db(){return new Promise((res,rej)=>{let r=indexedDB.open('alnwickGhostArchive',1);r.onupgradeneeded=()=>r.result.createObjectStore('photos',{keyPath:'id',autoIncrement:true});r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}async function dbAdd(p){let d=await db();return new Promise((res,rej)=>{let t=d.transaction('photos','readwrite'),r=t.objectStore('photos').add(p);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}async function dbAll(){let d=await db();return new Promise((res,rej)=>{let r=d.transaction('photos').objectStore('photos').getAll();r.onsuccess=()=>res(r.result.reverse());r.onerror=()=>rej(r.error)})}window.downloadPhoto=async id=>{let all=await dbAll(),p=all.find(x=>x.id===id);if(p){let a=document.createElement('a');a.href=p.data;a.download=`alnwick-ghost-${id}.jpg`;a.click()}};
applySettings();document.addEventListener('play',e=>{if(e.target.tagName==='AUDIO')e.target.muted=!state.settings.sound},true);
let q=new URLSearchParams(location.search),caseId=Number(q.get('case'));if(!state.name)landing();else{seedMessages();if(caseId>=1&&caseId<=10){hunt();setTimeout(()=>openCase(caseId),50)}else go((location.hash||'#hunt').slice(1))}
